//! OpenAPI schema generation via utoipa.
//!
//! Every routed handler carries a `#[utoipa::path]` annotation and is
//! registered in `paths()` below; the spec is served at
//! `GET /api/docs/openapi.json` and rendered by the Scalar console at
//! `/api/docs`. Handlers behind wildcard routes (`/api/images/*path`,
//! `/api/extensions/:id/assets/*asset_path`, `/api/share/:token/proxy/*path`,
//! `/api/docs/*rest`) are not representable as OpenAPI templates and stay
//! discoverable via `/api/docs/routes.json` (the CI-enforced route index).
//!
//! Adding an endpoint: derive `utoipa::path` on the handler (params,
//! request body, responses with the shapes from the handler's DTOs), add it
//! to `paths()` below, and extend the drift test if it's a new router.

use utoipa::OpenApi;

/// The HeraMind OpenAPI document. `info` describes the service; `paths` is
/// hand-maintained alongside the handlers it documents — the api_docs drift
/// test fails when an annotated path is not actually routed.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "HeraMind API",
        version = "0.9.24",
        description = "Edge AI/IoT platform API. All responses use the \
{success, data|error:{code,message}} envelope. Timestamps are Unix seconds \
unless a field is documented otherwise. Interactive docs: /api/docs; full \
route index (including not-yet-schematized endpoints): /api/docs/routes.json."
    ),
    paths(
        // ---- Auth ----
        crate::handlers::auth_users::login_handler,
        crate::handlers::auth_users::register_handler,
        crate::handlers::auth::create_key_handler,
        crate::handlers::auth::list_keys_handler,
        // ---- Devices ----
        crate::handlers::devices::crud::list_devices_handler,
        crate::handlers::devices::crud::add_device_handler,
        crate::handlers::devices::crud::get_device_handler,
        crate::handlers::devices::crud::update_device_handler,
        crate::handlers::devices::crud::delete_device_handler,
        crate::handlers::devices::crud::get_device_current_handler,
        // ---- Telemetry ----
        crate::handlers::devices::telemetry::get_device_telemetry_handler,
        crate::handlers::devices::telemetry::get_device_telemetry_summary_handler,
        crate::handlers::devices::metrics::write_metric_handler,
        crate::handlers::devices::metrics::send_command_handler,
        // ---- auth ----
        crate::handlers::auth::auth_status_handler,
        crate::handlers::auth::delete_key_handler,
        crate::handlers::auth_users::get_auth_status_handler,
        crate::handlers::auth_users::get_current_user_handler,
        crate::handlers::auth_users::logout_handler,
        crate::handlers::auth_users::change_password_handler,
        crate::handlers::auth_users::list_users_handler,
        crate::handlers::auth_users::create_user_handler,
        crate::handlers::auth_users::delete_user_handler,
        // ---- setup ----
        crate::handlers::setup::setup_status_handler,
        crate::handlers::setup::initialize_admin_handler,
        crate::handlers::setup::complete_setup_handler,
        crate::handlers::setup::save_llm_config_handler,
        // ---- health ----
        crate::handlers::basic::health_handler,
        crate::handlers::basic::health_status_handler,
        crate::handlers::basic::liveness_handler,
        crate::handlers::basic::readiness_handler,
        // ---- system ----
        crate::handlers::api_docs::docs_handler,
        crate::handlers::api_docs::routes_json_handler,
        crate::handlers::basic::network_info_handler,
        crate::handlers::basic::metrics_handler,
        // ---- devices ----
        crate::handlers::devices::webhook::webhook_handler,
        crate::handlers::devices::webhook::webhook_generic_handler,
        crate::handlers::devices::webhook::get_webhook_url_handler,
        crate::handlers::devices::ble_provision::ble_provision_handler,
        crate::handlers::devices::mdl::generate_mdl_handler,
        crate::handlers::devices::crud::get_devices_current_batch_handler,
        // ---- drafts ----
        crate::handlers::devices::auto_onboard::list_draft_devices,
        crate::handlers::devices::auto_onboard::get_draft_device,
        crate::handlers::devices::auto_onboard::update_draft_device,
        crate::handlers::devices::auto_onboard::approve_draft_device,
        crate::handlers::devices::auto_onboard::reject_draft_device,
        crate::handlers::devices::auto_onboard::trigger_draft_analysis,
        crate::handlers::devices::auto_onboard::enhance_draft_with_llm,
        crate::handlers::devices::auto_onboard::suggest_device_types,
        crate::handlers::devices::auto_onboard::cleanup_draft_devices,
        crate::handlers::devices::auto_onboard::get_type_signatures,
        crate::handlers::devices::auto_onboard::get_onboard_config,
        crate::handlers::devices::auto_onboard::update_onboard_config,
        crate::handlers::devices::auto_onboard::upload_device_data,
        // ---- device-types ----
        crate::handlers::devices::types::list_cloud_device_types_handler,
        crate::handlers::devices::types::list_device_types_handler,
        crate::handlers::devices::types::get_device_type_handler,
        crate::handlers::devices::types::register_device_type_handler,
        crate::handlers::devices::types::validate_device_type_handler,
        crate::handlers::devices::types::delete_device_type_handler,
        crate::handlers::devices::types::import_cloud_device_types_handler,
        // ---- telemetry ----
        crate::handlers::devices::telemetry::get_device_command_history_handler,
        crate::handlers::devices::telemetry_stats::get_telemetry_stats_handler,
        crate::handlers::data::query_telemetry_handler,
        crate::handlers::data::list_all_data_sources_handler,
        // ---- stats ----
        crate::handlers::stats::get_system_stats_handler,
        crate::handlers::stats::get_device_stats_handler,
        crate::handlers::stats::get_rule_stats_handler,
        // ---- dashboards ----
        crate::handlers::dashboards::list_dashboards_handler,
        crate::handlers::dashboards::create_dashboard_handler,
        crate::handlers::dashboards::reorder_dashboards_handler,
        crate::handlers::dashboards::get_dashboard_handler,
        crate::handlers::dashboards::update_dashboard_handler,
        crate::handlers::dashboards::delete_dashboard_handler,
        crate::handlers::dashboards::add_components_handler,
        crate::handlers::dashboards::update_component_handler,
        crate::handlers::dashboards::remove_components_handler,
        crate::handlers::dashboards::set_default_dashboard_handler,
        crate::handlers::dashboards::duplicate_dashboard_handler,
        crate::handlers::dashboards::list_templates_handler,
        crate::handlers::dashboards::get_template_handler,
        // ---- shares ----
        crate::handlers::dashboards::get_shared_dashboard_handler,
        crate::handlers::dashboards::create_share_handler,
        crate::handlers::dashboards::list_shares_handler,
        crate::handlers::dashboards::revoke_share_handler,
        // ---- rules ----
        crate::handlers::rules::list_rules_handler,
        crate::handlers::rules::create_rule_handler,
        crate::handlers::rules::export_rules_handler,
        crate::handlers::rules::import_rules_handler,
        crate::handlers::rules::get_resources_handler,
        crate::handlers::rules::validate_rule_handler,
        crate::handlers::rules::get_rule_handler,
        crate::handlers::rules::update_rule_handler,
        crate::handlers::rules::delete_rule_handler,
        crate::handlers::rules::set_rule_status_handler,
        crate::handlers::rules::test_rule_handler,
        crate::handlers::rules::trigger_rule_handler,
        crate::handlers::rules::get_rule_history_handler,
        // ---- automations ----
        crate::handlers::automations::list_automations_handler,
        crate::handlers::automations::create_automation_handler,
        crate::handlers::automations::export_automations_handler,
        crate::handlers::automations::import_automations_handler,
        crate::handlers::automations::analyze_intent_handler,
        crate::handlers::automations::list_templates_handler,
        crate::handlers::automations::get_automation_handler,
        crate::handlers::automations::update_automation_handler,
        crate::handlers::automations::delete_automation_handler,
        crate::handlers::automations::set_automation_status_handler,
        crate::handlers::automations::get_automations_executions_handler,
        // ---- transforms ----
        crate::handlers::automations::process_data_handler,
        crate::handlers::automations::test_transform_handler,
        crate::handlers::automations::test_transform_code_handler,
        crate::handlers::automations::list_transforms_handler,
        crate::handlers::automations::list_virtual_metrics_handler,
        crate::handlers::automations::list_transform_data_sources_handler,
        crate::handlers::automations::get_transform_data_sources_handler,
        crate::handlers::automations::get_transform_data_source_handler,
        // ---- agents ----
        crate::handlers::agents::list_agents,
        crate::handlers::agents::create_agent,
        crate::handlers::agents::list_agent_tools,
        crate::handlers::agents::get_agent,
        crate::handlers::agents::update_agent,
        crate::handlers::agents::delete_agent,
        crate::handlers::agents::execute_agent,
        crate::handlers::agents::invoke_agent,
        crate::handlers::agents::set_agent_status,
        crate::handlers::agents::get_agent_executions,
        crate::handlers::agents::get_execution,
        crate::handlers::agents::batch_get_executions,
        crate::handlers::agents::get_agent_memory,
        crate::handlers::agents::clear_agent_memory,
        crate::handlers::agents::get_agent_stats,
        crate::handlers::agents::get_available_resources,
        crate::handlers::agents::validate_cron_expression,
        crate::handlers::agents::validate_llm_backend,
        crate::handlers::agents::get_user_messages,
        crate::handlers::agents::add_user_message,
        crate::handlers::agents::clear_user_messages,
        crate::handlers::agents::delete_user_message,
        // ---- skills ----
        crate::handlers::skills::list_skills_handler,
        crate::handlers::skills::match_skills_handler,
        crate::handlers::skills::get_skill_handler,
        crate::handlers::skills::create_skill_handler,
        crate::handlers::skills::reload_skills_handler,
        crate::handlers::skills::update_skill_handler,
        crate::handlers::skills::delete_skill_handler,
        // ---- memory ----
        crate::handlers::memory::get_all_memory,
        crate::handlers::memory::export_all,
        crate::handlers::memory::get_stats,
        crate::handlers::memory::get_config,
        crate::handlers::memory::update_config,
        crate::handlers::memory::trigger_compress,
        crate::handlers::memory::get_category,
        crate::handlers::memory::update_category,
        crate::handlers::memory::get_memory_content,
        crate::handlers::memory::update_memory_content,
        crate::handlers::memory::delete_memory_file,
        crate::handlers::memory::get_memory_file,
        crate::handlers::memory::update_memory_file,
        crate::handlers::memory::list_custom_files,
        crate::handlers::memory::get_custom_file,
        crate::handlers::memory::update_custom_file,
        crate::handlers::memory::delete_custom_file,
        // ---- sessions ----
        crate::handlers::sessions::ws_chat_handler,
        crate::handlers::sessions::create_session_handler,
        crate::handlers::sessions::list_sessions_handler,
        crate::handlers::sessions::cleanup_sessions_handler,
        crate::handlers::sessions::get_session_handler,
        crate::handlers::sessions::get_session_history_handler,
        crate::handlers::sessions::update_session_handler,
        crate::handlers::sessions::toggle_memory_handler,
        crate::handlers::sessions::delete_session_handler,
        crate::handlers::sessions::chat_handler,
        crate::handlers::sessions::get_pending_stream_handler,
        crate::handlers::sessions::clear_pending_stream_handler,
        // ---- llm-backends ----
        crate::handlers::llm_backends::list_backend_types_handler,
        crate::handlers::llm_backends::get_backend_schema_handler,
        crate::handlers::llm_backends::list_backends_handler,
        crate::handlers::llm_backends::get_backend_handler,
        crate::handlers::llm_backends::get_backend_stats_handler,
        crate::handlers::llm_backends::list_ollama_models_handler,
        crate::handlers::llm_backends::list_llamacpp_server_info_handler,
        crate::handlers::llm_backends::create_backend_handler,
        crate::handlers::llm_backends::update_backend_handler,
        crate::handlers::llm_backends::delete_backend_handler,
        crate::handlers::llm_backends::activate_backend_handler,
        crate::handlers::llm_backends::test_backend_handler,
        crate::handlers::llm_backends::update_capabilities_override_handler,
        crate::handlers::settings::llm_generate_handler,
        // ---- builtin-llm ----
        crate::builtin_llm::handlers::status_handler,
        crate::builtin_llm::handlers::models_handler,
        crate::builtin_llm::handlers::download_handler,
        crate::builtin_llm::handlers::download_cancel_handler,
        crate::builtin_llm::handlers::import_local_handler,
        crate::builtin_llm::handlers::upload_model_handler,
        crate::builtin_llm::handlers::delete_model_handler,
        crate::builtin_llm::handlers::restart_handler,
        crate::builtin_llm::handlers::activate_handler,
        // ---- instances ----
        crate::handlers::instances::list_instances_handler,
        crate::handlers::instances::create_instance_handler,
        crate::handlers::instances::get_instance_handler,
        crate::handlers::instances::update_instance_handler,
        crate::handlers::instances::delete_instance_handler,
        crate::handlers::instances::test_instance_handler,
        // ---- messages ----
        crate::handlers::messages::list_messages_handler,
        crate::handlers::messages::create_message_handler,
        crate::handlers::messages::message_stats_handler,
        crate::handlers::messages::cleanup_handler,
        crate::handlers::messages::bulk_acknowledge_handler,
        crate::handlers::messages::bulk_resolve_handler,
        crate::handlers::messages::bulk_delete_handler,
        crate::handlers::messages::get_message_handler,
        crate::handlers::messages::delete_message_handler,
        crate::handlers::messages::acknowledge_message_handler,
        crate::handlers::messages::resolve_message_handler,
        crate::handlers::messages::archive_message_handler,
        // ---- channels ----
        crate::handlers::message_channels::list_channel_types_handler,
        crate::handlers::message_channels::get_channel_type_schema_handler,
        crate::handlers::message_channels::list_channels_handler,
        crate::handlers::message_channels::get_channel_handler,
        crate::handlers::message_channels::get_channel_stats_handler,
        crate::handlers::message_channels::create_channel_handler,
        crate::handlers::message_channels::delete_channel_handler,
        crate::handlers::message_channels::update_channel_handler,
        crate::handlers::message_channels::test_channel_handler,
        crate::handlers::message_channels::list_recipients_handler,
        crate::handlers::message_channels::add_recipient_handler,
        crate::handlers::message_channels::remove_recipient_handler,
        crate::handlers::message_channels::get_channel_filter_handler,
        crate::handlers::message_channels::update_channel_filter_handler,
        crate::handlers::message_channels::toggle_enabled_handler,
        // ---- data-push ----
        crate::handlers::data_push::list_push_targets_handler,
        crate::handlers::data_push::create_push_target_handler,
        crate::handlers::data_push::get_push_stats_handler,
        crate::handlers::data_push::get_push_target_handler,
        crate::handlers::data_push::update_push_target_handler,
        crate::handlers::data_push::delete_push_target_handler,
        crate::handlers::data_push::test_push_target_handler,
        crate::handlers::data_push::start_push_target_handler,
        crate::handlers::data_push::stop_push_target_handler,
        crate::handlers::data_push::list_delivery_logs_handler,
        // ---- im-bridges ----
        crate::handlers::im_bridges::list_bridges_handler,
        crate::handlers::im_bridges::list_invites_handler,
        crate::handlers::im_bridges::list_allowlist_handler,
        crate::handlers::im_bridges::list_sessions_handler,
        crate::handlers::im_bridges::create_bridge_handler,
        crate::handlers::im_bridges::delete_bridge_handler,
        crate::handlers::im_bridges::create_invite_handler,
        crate::handlers::im_bridges::revoke_invite_handler,
        crate::handlers::im_bridges::remove_allowlist_handler,
        crate::handlers::im_bridges::reset_session_handler,
        // ---- extensions ----
        crate::handlers::extensions::list_extensions_handler,
        crate::handlers::extensions::list_extension_types_handler,
        crate::handlers::extensions::get_all_dashboard_components_handler,
        crate::handlers::extensions::list_extension_capabilities_handler,
        crate::handlers::extensions::get_extension_handler,
        crate::handlers::extensions::extension_health_handler,
        crate::handlers::extensions::list_extension_commands_handler,
        crate::handlers::extensions::get_extension_components_handler,
        crate::handlers::extensions::get_event_subscriptions_handler,
        crate::handlers::extensions::unregister_extension_handler,
        crate::handlers::extensions::set_extension_enabled_handler,
        crate::handlers::extensions::set_extension_command_enabled_handler,
        crate::handlers::extensions::get_extension_logs_handler,
        crate::handlers::extensions::clear_extension_logs_handler,
        crate::handlers::extensions::get_extension_descriptor_handler,
        crate::handlers::extensions::list_extension_data_sources_handler,
        crate::handlers::extensions::query_extension_metric_data_handler,
        crate::handlers::extensions::push_extension_metrics_handler,
        crate::handlers::extensions::execute_extension_command_handler,
        crate::handlers::extensions::invoke_extension_handler,
        crate::handlers::extensions::reload_extension_handler,
        crate::handlers::extensions::list_marketplace_extensions_handler,
        crate::handlers::extensions::get_marketplace_extension_handler,
        crate::handlers::extensions::get_marketplace_extension_readme_handler,
        crate::handlers::extensions::check_marketplace_updates_handler,
        crate::handlers::extensions::register_extension_handler,
        crate::handlers::extensions::uninstall_extension_handler,
        crate::handlers::extensions::start_extension_handler,
        crate::handlers::extensions::stop_extension_handler,
        crate::handlers::extensions::get_extension_config_handler,
        crate::handlers::extensions::update_extension_config_handler,
        crate::handlers::extensions::install_marketplace_extension_handler,
        crate::handlers::extensions::sync_extensions_handler,
        crate::handlers::extensions::get_sync_status_handler,
        crate::handlers::extensions::upload_extension_file_handler,
        crate::handlers::extension_stream::get_stream_capability_handler,
        crate::handlers::extension_stream::list_stream_sessions_handler,
        crate::handlers::extension_stream::extension_stream_ws,
        // ---- frontend-components ----
        crate::handlers::frontend_components::market_list_handler,
        crate::handlers::frontend_components::get_bundle_handler,
        crate::handlers::frontend_components::install_component_from_path_handler,
        crate::handlers::frontend_components::market_install_handler,
        crate::handlers::frontend_components::check_updates_handler,
        crate::handlers::frontend_components::list_components_handler,
        crate::handlers::frontend_components::get_component_handler,
        crate::handlers::frontend_components::uninstall_component_handler,
        crate::handlers::frontend_components::install_component_handler,
        // ---- mqtt ----
        crate::handlers::mqtt::status::get_mqtt_status_handler,
        crate::handlers::mqtt::subscriptions::list_subscriptions_handler,
        crate::handlers::mqtt::subscriptions::subscribe_handler,
        crate::handlers::mqtt::subscriptions::unsubscribe_handler,
        crate::handlers::mqtt::subscriptions::subscribe_device_handler,
        crate::handlers::mqtt::subscriptions::unsubscribe_device_handler,
        crate::handlers::mqtt::brokers::list_brokers_handler,
        crate::handlers::mqtt::brokers::create_broker_handler,
        crate::handlers::mqtt::brokers::get_broker_handler,
        crate::handlers::mqtt::brokers::update_broker_handler,
        crate::handlers::mqtt::brokers::delete_broker_handler,
        crate::handlers::mqtt::brokers::test_broker_handler,
        crate::handlers::mqtt::broker_config::get_broker_config_handler,
        crate::handlers::mqtt::broker_config::update_broker_config_handler,
        crate::handlers::mqtt::broker_config::add_credential_handler,
        crate::handlers::mqtt::broker_config::delete_credential_handler,
        crate::handlers::mqtt::broker_config::upload_tls_handler,
        crate::handlers::mqtt::broker_config::generate_tls_handler,
        crate::handlers::mqtt::broker_config::download_ca_cert_handler,
        // ---- events ----
        crate::handlers::events::event_websocket_handler,
        crate::handlers::events::event_stream_handler,
        crate::handlers::events::publish_event_handler,
        // ---- capabilities ----
        crate::handlers::capabilities::list_capabilities_handler,
        crate::handlers::capabilities::get_capability_handler,
        // ---- tools ----
        crate::handlers::tools::list_tools_handler,
        crate::handlers::tools::get_tool_handler,
        // ---- suggestions ----
        crate::handlers::suggestions::get_suggestions_handler,
        crate::handlers::suggestions::get_suggestions_categories_handler,
        // ---- settings ----
        crate::handlers::auth_users::get_registration_settings_handler,
        crate::handlers::auth_users::update_registration_settings_handler,
        crate::handlers::settings::get_timezone,
        crate::handlers::settings::update_timezone,
        crate::handlers::settings::list_timezones,
        crate::handlers::settings::get_retention_config,
        crate::handlers::settings::update_retention_config,
        crate::handlers::settings::get_backup_config,
        crate::handlers::settings::update_backup_config,
        crate::handlers::settings::trigger_retention_cleanup,
        crate::handlers::settings::get_agent_defaults,
        crate::handlers::settings::update_agent_defaults,
        crate::handlers::settings::get_device_defaults,
        crate::handlers::settings::update_device_defaults,
        crate::handlers::settings::get_market_source_handler,
        crate::handlers::settings::update_market_source_handler,
        // ---- backups ----
        crate::handlers::settings::create_backup_handler,
        crate::handlers::settings::list_backups_handler,
        // ---- config ----
        crate::handlers::config::export_config_handler,
        crate::handlers::config::import_config_handler,
        crate::handlers::config::validate_config_handler,
        // ---- upgrades ----
        crate::handlers::system::upgrade_check_handler,
        crate::handlers::system::start_upgrade_handler,
        crate::handlers::system::upgrade_status_handler,
        // ---- logs ----
        crate::handlers::logs::download_logs_handler,
        // ---- onboarding ----
        crate::handlers::onboarding::get_onboarding_status_handler,
        crate::handlers::onboarding::dismiss_onboarding_handler,
        crate::handlers::onboarding::reset_onboarding_handler,
    ),
    tags(
        (name = "auth", description = "Login, registration, API keys, user admin"),
        (name = "setup", description = "First-run setup wizard"),
        (name = "health", description = "Liveness, readiness, component health"),
        (name = "system", description = "Server info, metrics, docs endpoints"),
        (name = "devices", description = "Device CRUD, webhooks, provisioning"),
        (name = "drafts", description = "Auto-discovered draft devices (onboarding queue)"),
        (name = "device-types", description = "Device-type templates (MDL registry)"),
        (name = "telemetry", description = "Time-series query, write, and commands"),
        (name = "stats", description = "Aggregate statistics"),
        (name = "dashboards", description = "Dashboard CRUD and components"),
        (name = "shares", description = "Public share links for dashboards"),
        (name = "rules", description = "Rule engine CRUD and execution"),
        (name = "automations", description = "Unified automations (rules + agents + transforms)"),
        (name = "transforms", description = "Data transforms and virtual metrics"),
        (name = "agents", description = "User-defined AI agents"),
        (name = "skills", description = "Skill catalog and matching"),
        (name = "memory", description = "Markdown-based system memory"),
        (name = "sessions", description = "Chat sessions (REST; WS chat at /api/chat)"),
        (name = "llm-backends", description = "LLM backend configuration and one-shot generation"),
        (name = "builtin-llm", description = "Bundled local model (LFM2.5) management"),
        (name = "instances", description = "Remote HeraMind instance registry"),
        (name = "messages", description = "Notification message feed"),
        (name = "channels", description = "Notification channels (email, IM, webhook)"),
        (name = "data-push", description = "Outbound data push targets"),
        (name = "im-bridges", description = "IM platform bridges (invites, allowlist, sessions)"),
        (name = "extensions", description = "Extension lifecycle, commands, marketplace"),
        (name = "frontend-components", description = "Frontend component install and marketplace"),
        (name = "mqtt", description = "MQTT subscriptions, external brokers, embedded broker config"),
        (name = "events", description = "Event publish and streaming (WS/SSE)"),
        (name = "capabilities", description = "Capability registry metadata"),
        (name = "tools", description = "Tool catalog metadata"),
        (name = "suggestions", description = "Input completion suggestions"),
        (name = "settings", description = "Server settings (timezone, retention, defaults)"),
        (name = "backups", description = "Data-directory backups"),
        (name = "config", description = "Configuration import/export"),
        (name = "upgrades", description = "Server self-upgrade"),
        (name = "logs", description = "Diagnostic log archive"),
        (name = "onboarding", description = "UI onboarding wizard state"),
    ),
    components(
        schemas(
crate::handlers::dashboards::AddComponentsRequest,
    crate::handlers::mqtt::broker_config::AddCredentialRequest,
    crate::handlers::devices::models::AddDeviceRequest,
    crate::handlers::message_channels::AddRecipientRequest,
    crate::handlers::agents::AddUserMessageRequest,
    crate::handlers::settings::AgentDefaultsRequest,
    crate::handlers::automations::AnalyzeIntentRequest,
    crate::handlers::devices::auto_onboard::ApproveDraftDeviceRequest,
    crate::automation::discovery::auto_onboard::AutoOnboardConfig,
    crate::handlers::settings::BackupConfigRequest,
    crate::handlers::devices::models::BatchCurrentValuesRequest,
    crate::handlers::agents::BatchExecutionIds,
    crate::handlers::devices::ble_provision::BleProvisionRequest,
    crate::handlers::messages::BulkAcknowledgeRequest,
    crate::auth_users::ChangePasswordRequest,
    crate::models::ChatRequest,
    crate::handlers::messages::CleanupRequest,
    crate::handlers::devices::types::CloudImportRequest,
    crate::handlers::config::ConfigExport,
    crate::handlers::config::ConfigImport,
    crate::handlers::agents::CreateAgentRequest,
    crate::handlers::automations::CreateAutomationRequest,
    crate::handlers::llm_backends::CreateBackendRequest,
    crate::handlers::im_bridges::CreateBridgeRequest,
    crate::handlers::message_channels::CreateChannelRequest,
    crate::handlers::dashboards::CreateDashboardRequest,
    crate::handlers::instances::CreateInstanceRequest,
    crate::handlers::auth::CreateKeyRequest,
    crate::handlers::messages::CreateMessageRequest,
    crate::models::CreateSessionRequest,
    crate::handlers::dashboards::CreateShareRequest,
    crate::handlers::skills::CreateSkillRequest,
    // EXTERNAL: CreateTargetRequest in crates/heramind-data-push/src/manager.rs
    crate::handlers::settings::DeviceDefaultsRequest,
    // EXTERNAL: DeviceTypeTemplate in crates/heramind-storage/src/device_registry.rs
    crate::handlers::agents::ExecuteAgentRequest,
    crate::handlers::extensions::ExecuteCommandRequest,
    crate::handlers::mqtt::brokers::ExternalBrokerRequest,
    crate::handlers::devices::models::GenerateMdlRequest,
    crate::handlers::setup::InitializeAdminRequest,
    crate::handlers::frontend_components::InstallFromPathRequest,
    crate::handlers::extensions::InvokeExtensionRequest,
    crate::handlers::setup::LlmConfigRequest,
    crate::handlers::settings::LlmGenerateRequest,
    crate::auth_users::LoginRequest,
    crate::auth_users::LoginResponse,
    crate::handlers::frontend_components::MarketInstallRequest,
    crate::handlers::settings::MarketSourceRequest,
    crate::handlers::extensions::MarketplaceInstallRequest,
    crate::handlers::skills::MatchTestRequest,
    crate::handlers::mqtt::models::MqttSubscribeRequest,
    crate::handlers::mqtt::models::MqttUnsubscribeRequest,
    crate::handlers::automations::ProcessDataRequest,
    crate::handlers::events::PublishEventRequest,
    crate::handlers::extensions::RegisterExtensionRequest,
    crate::auth_users::RegisterRequest,
    crate::handlers::devices::auto_onboard::RejectDraftDeviceRequest,
    crate::handlers::dashboards::RemoveComponentsRequest,
    crate::handlers::dashboards::ReorderDashboardsRequest,
    crate::handlers::settings::RetentionConfigRequest,
    crate::handlers::automations::SetAutomationStatusRequest,
    crate::handlers::rules::SetRuleStatusRequest,
    crate::handlers::extensions::SetToolEnabledRequest,
    crate::handlers::automations::TestTransformCodeRequest,
    crate::handlers::settings::TimezoneRequest,
    crate::handlers::message_channels::ToggleEnabledRequest,
    crate::handlers::sessions::ToggleMemoryRequest,
    crate::handlers::agents::UpdateAgentRequest,
    crate::handlers::automations::UpdateAutomationRequest,
    crate::handlers::llm_backends::UpdateBackendRequest,
    crate::handlers::mqtt::broker_config::UpdateBrokerConfigRequest,
    crate::handlers::llm_backends::UpdateCapabilitiesOverrideRequest,
    crate::handlers::message_channels::UpdateChannelRequest,
    crate::handlers::dashboards::UpdateComponentRequest,
    crate::handlers::memory::UpdateConfigRequest,
    crate::handlers::dashboards::UpdateDashboardRequest,
    crate::handlers::devices::models::UpdateDeviceRequest,
    crate::handlers::devices::auto_onboard::UpdateDraftDeviceRequest,
    crate::handlers::message_channels::UpdateFilterRequest,
    crate::handlers::instances::UpdateInstanceRequest,
    crate::handlers::memory::UpdateMemoryRequest,
    crate::handlers::auth_users::UpdateRegistrationSettingsRequest,
    crate::handlers::sessions::UpdateSessionRequest,
    // EXTERNAL: UpdateTargetRequest in crates/heramind-data-push/src/manager.rs
    crate::handlers::devices::auto_onboard::UploadDeviceDataRequest,
    crate::handlers::extensions::UploadExtensionFileRequest,
    crate::handlers::mqtt::broker_config::UploadTlsRequest,
    crate::handlers::agents::ValidateCronRequest,
    crate::handlers::agents::ValidateLlmRequest,
    crate::handlers::devices::metrics::WriteMetricRequest,
    crate::handlers::agents::AgentResourceRequest,
    crate::handlers::agents::AgentScheduleRequest,
    crate::handlers::config::AlertsExport,
    crate::automation::types::AutomationType,
    crate::models::ChatImage,
    crate::handlers::agents::CommandSelectionRequest,
    crate::handlers::config::ConfigImportOptions,
    crate::handlers::dashboards::CreateDashboardComponent,
    crate::handlers::dashboards::DashboardLayout,
    crate::handlers::config::DevicesExport,
    crate::handlers::config::LlmSettingsExport,
    crate::handlers::agents::MetricSelectionRequest,
    crate::handlers::devices::auto_onboard::NewTypeDetails,
    crate::handlers::agents::ResourceRequest,
    crate::handlers::config::RulesExport,
    crate::models::SessionConfigPatch,
    crate::handlers::dashboards::SharePermissions,
    crate::auth_users::UserInfo,
    crate::auth_users::UserRole,
    heramind_agent::agent::types::AgentConfig,
    heramind_storage::llm_backends::BackendCapabilities,
    heramind_data_push::CreateTargetRequest,
    heramind_data_push::UpdateTargetRequest,
    heramind_storage::device_registry::DeviceTypeTemplate,
    heramind_storage::memory_config::MemoryConfig,
    crate::models::ThinkingEffortMirror,
    crate::models::AgentToolConfigMirror,
    crate::handlers::config::AlertRuleExport,
    heramind_data_push::types::BatchConfig,
    heramind_storage::device_registry::CommandDefinition,
    crate::handlers::dashboards::ComponentPosition,
    heramind_data_push::types::DataSourceFilter,
    crate::handlers::config::DeviceConfigExport,
    heramind_storage::device_registry::DeviceTypeMode,
    crate::handlers::config::ImportSections,
    crate::handlers::dashboards::LayoutBreakpoints,
    heramind_storage::device_registry::MetricDefinition,
    heramind_data_push::types::PushSchedule,
    heramind_storage::llm_backends::ReasoningCapabilities,
    heramind_data_push::types::RetryConfig,
    crate::handlers::dashboards::RowsValue,
    crate::handlers::config::RuleConfigExport,
    heramind_data_push::types::BatchFormat,
    heramind_storage::device_registry::MetricDataType,
    heramind_storage::device_registry::ParameterDefinition,
    heramind_storage::device_registry::ParameterGroup,
    crate::handlers::llm_backends::BackendInstanceDto,
    heramind_storage::device_registry::ValidationRule,
    heramind_storage::device_registry::ParamMetricValue,
        )
    ),
)]
pub struct ApiDoc;

/// GET /api/docs/openapi.json — the machine-readable OpenAPI 3 document.
pub async fn openapi_json_handler() -> axum::Json<utoipa::openapi::OpenApi> {
    axum::Json(ApiDoc::openapi())
}
